// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type Comment struct {
	ID        string  `json:"id"`
	Content   string  `json:"content"`
	Author    string  `json:"author"`
	PostID    string  `json:"postId"`
	ParentID  *string `json:"parentId,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

type Mutation struct {
}

type NewAuthor struct {
	Username string `json:"username"`
}

type NewComment struct {
	Content  string  `json:"content"`
	Author   string  `json:"author"`
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
}

type NewPost struct {
	Title           string `json:"title"`
	Content         string `json:"content"`
	Author          string `json:"author"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Post struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Content         string `json:"content"`
	Author          string `json:"author"`
	CommentsEnabled bool   `json:"commentsEnabled"`
	CreatedAt       string `json:"createdAt"`
}

type Query struct {
}
